//
//  RunAid.swift
//  RunAid
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class RunAidUser: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _username: String?
    var _deviceId: String?
    var _emailAddress: String?
    var _emergencyContacts: [[String:String]]?
    var _phoneNumber: String?
    
    class func dynamoDBTableName() -> String {

        return "runaid-mobilehub-56721510-RunAid"
    }
    
    class func hashKeyAttribute() -> String {

        return "_username"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_username" : "username",
               "_deviceId" : "device id",
               "_emailAddress" : "email address",
               "_emergencyContacts" : "emergency contacts",
               "_phoneNumber" : "phone number",
        ]
    }
}
