//
//  TestTable.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class TestTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _deviceId: String?
    var _emailAddress: String?
    var _emergencyContacts: [[String:String]]?
    var _phoneNumber: String?
    
    class func dynamoDBTableName() -> String {

        return "runaid-mobilehub-56721510-TestTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_deviceId" : "deviceId",
               "_emailAddress" : "email address",
               "_emergencyContacts" : "emergency contacts",
               "_phoneNumber" : "phone number",
        ]
    }
}
